<?php

/**
 * @file 
 * This file demonstrates how to use hook functions.
 */

use Drupal\Core\Url;

/**
* Implements hook_form_alter().
*/
function block_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  \Drupal::messenger()->addMessage(t("Form id of this form is @id:",['@id' => $form_id]));
  $form['#submit'][] = 'block_module_user_login_submit';
}

/**
 * Form submission handler for user_login_form().
 *
 * Redirects the user to the /custom-welcome-page after logging in.
 */
function block_module_user_login_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $url = Url::fromRoute('block_module.my_page');
  $form_state->setRedirectUrl($url);
}
