<?php

/**
 * @file 
 * This file demonstrates how to use hook functions.
 */


/**
 * Implements hook_cron().
 */
function module3_cron() {
  \Drupal::messenger()->addMessage(t("Hello from Module 3 cron hook!!"));

  if (\Drupal::currentUser()->hasPermission('static permission 2')) {
    \Drupal::messenger()->addMessage(t("You Have static permission 2!"));
  }
  else {
    \Drupal::messenger()->addMessage(t("You  DO NOT have static permission 2!"));
  }
}

/**
 * Implements hook_form_alter().
 */
function module3_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  \Drupal::messenger()->addMessage(t("Form id of this form is @id:",['@id' => $form_id]));
  if ($form_id == 'node_article_form') {
    $form['actions']['submit']['#value'] = t("Save this awesome article!");
  }

}
